import { data } from '../data/data.js'
import { veryficationLogaut } from './login-page/validateLogin.js'
import { showPanelIconMobile } from './modules/panel-top.js'
import { showStart, showTasks, observeSection } from './modules/nav.js'
import { startWork } from './modules/start.js'
